#!/bin/bash

EXECUTE_PATH=$(pwd)
SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd)
TEMPLATES=$(ls -d */ | cut -f1 -d'/') #("python-cpu" "python-gpu" "python-gpu-conda")

help () {
    # Display Help
   echo "Usage: generate-template [template_name] [project_name]"
   echo "arguments:"
   echo "   template_name: one of [$(echo ${TEMPLATES})]"
   echo "   project_name: output project name"
}

contains() {
    for entity in $1; do
        if [ "$entity" = "$2" ]; then
            return 0
        fi
    done
    return 1
}

validate_arguments ()
{   
    if [ $# -eq 2 ] && contains "${TEMPLATES[*]}" "$TEMPLATE_NAME" ; then
        :
    else
        help
        exit 1
    fi
}

TEMPLATE_NAME="$1"
PROJECT_NAME="$2"

validate_arguments "$@"

TEMPLATE_PATH="$SCRIPT_PATH/$TEMPLATE_NAME"
PROJECT_PATH="$EXECUTE_PATH/$PROJECT_NAME"

cp -R ${TEMPLATE_PATH} ${PROJECT_PATH}

find "$PROJECT_PATH" -type f |
{
    while IFS= read -r file; do
        sed -i "s/\[PROJECT_NAME\]/$PROJECT_NAME/g" "$file"
    done
}
