version: "3.0"
services:
  app:
    container_name: [PROJECT_NAME]-app-dev
    image: [PROJECT_NAME]_app-dev:latest
    volumes:
      - ../:/root/[PROJECT_NAME]/
      - pypackages-[PROJECT_NAME]:/root/[PROJECT_NAME]/__pypackages__/
      - cache:/root/.cache
      - ~/.ssh/:/root/.ssh/:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    ports:
      - ${port:-8888}:8888
volumes:
  pypackages-[PROJECT_NAME]:
  cache:
    external: true
    name: local-cache