version: "3.0"
services:
  app:
    container_name: [PROJECT_NAME]-app
    image: [PROJECT_NAME]_app:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${ENV}
    environment:
      - SHELL=/bin/bash
    tty: true
    runtime: nvidia
