version: "3.0"
services:
  app:
    container_name: [PROJECT_NAME]-app-dev
    image: [PROJECT_NAME]_app-dev:latest
    volumes:
      - ../:/root/[PROJECT_NAME]/
      - pypackages-python-gpu-[PROJECT_NAME]:/root/[PROJECT_NAME]/__pypackages__/
      - cache:/root/.cache
      - ${MODEL_PATH}:/root/[PROJECT_NAME]/models
      - ${LOG_PATH}:/root/[PROJECT_NAME]/logs
      - ${DATASET_PATH}:/root/[PROJECT_NAME]/datasets
      - ~/.ssh/:/root/.ssh/:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    ports:
      - ${JUPYTER_PORT:-8888}:8888
volumes:
  pypackages-python-gpu-[PROJECT_NAME]:
  cache:
    external: true
    name: local-cache